### ISSUE TITLE
Support retry for gsutil actions

### ISSUE THREAD

**Issue by nmousavi** [googlegenomics/pipelines-tools#90] opened 2018-12-10 21:50 UTC
We got reports that DV fails when files are going to be localized/delocalized with the err

make_examples.py:1138] Created 15521 examples
Your "GCE" credentials are invalid. Please run
$ gcloud auth login
Could not reach metadata service: [Errno 111] Connection refused
CommandException: 1 file/object could not be transferred.

 gsutil retry can mitigate the known metadataserver issue.

**Comment by kemp-google** [comment] 2018-12-10 22:40
Duplicate of issue #89

**Closed** 2018-12-10 22:40 UTC
